name : Merge Request Workflow
on:
  pull_request:
jobs :
  MVN_clean :
    runs-on: ubuntu-latest
    steps :
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
           java-version: '17'
           distribution: 'temurin'
           cache: 'maven'
      - run: mvn clean install
  Spotless-check :
    runs-on : ubuntu-latest
    needs: MVN_clean
    steps :
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
           java-version: '17'
           distribution: 'temurin'
           cache: 'maven'
      - run : mvn spotless:check
