name : PR Check Workflow
on:
  pull_request:
jobs :
  Checklist_check :
    runs-on : ubuntu-latest
    steps :
      - name: Checkout code
        uses: actions/checkout@v2
      - run : mvn clean install
